package org.clean.string

import java.text.Normalizer

/**
 * @author wasim
 */

class FixChar {
    private static final List<Character>[] lookup = new List<Character>[10000]

    static String removeSpecialCharacter(String text) {
        List<Character> extraChar = []

        // Initializing lookup....
        if (!(lookup - null)) {
            lookupInit()
        }

        //Iterate over dirty String to get clean string from lookup method
        for(char ch: text.toCharArray()) {
            extraChar += lookup[(int) ch] ?: [ch]
        }
        char[] text_char = extraChar as char[]

        return Normalizer.normalize(String.valueOf(text_char).trim(), Normalizer.Form.NFD).replaceAll("[^\\p{ASCII}]", "")
    }

    private static lookupInit() {
        lookup[0] = [' ']
        lookup[1] = [' ']
        lookup[2] = [' ']
        lookup[3] = [' ']
        lookup[4] = [' ']
        lookup[5] = [' ']
        lookup[6] = [' ']
        lookup[7] = [' ']
        lookup[8] = [' ']
        lookup[11] = [' ']
        lookup[12] = [' ']
        lookup[14] = [' ']
        lookup[15] = [' ']
        lookup[16] = [' ']
        lookup[17] = [' ']
        lookup[18] = [' ']
        lookup[19] = [' ']
        lookup[20] = [' ']
        lookup[21] = [' ']
        lookup[22] = [' ']
        lookup[23] = [' ']
        lookup[24] = [' ']
        lookup[25] = [' ']
        lookup[26] = [' ']
        lookup[27] = [' ']
        lookup[28] = [' ']
        lookup[29] = [' ']
        lookup[31] = [' ']
        lookup[30] = [' ']
        lookup[102] = ['f']
        lookup[127] = [' ']
        lookup[128] = ['E']
        lookup[129] = [' ']
        lookup[130] = [',']
        lookup[131] = ['f']
        lookup[132] = [' ']
        lookup[133] = ['.', '.', '.']
        lookup[134] = ['(', 't', ')']
        lookup[135] = ['(', 't', 't', ')']
        lookup[136] = ['^']
        lookup[137] = ['%']
        lookup[138] = ['S']
        lookup[139] = ['<']
        lookup[140] = ['O', 'E']
        lookup[141] = [' ']
        lookup[142] = ['Z']
        lookup[143] = [' ']
        lookup[144] = [' ']
        lookup[145] = [' ']
        lookup[146] = [' ']
        lookup[147] = [' ']
        lookup[148] = [' ']
        lookup[149] = [' ']
        lookup[150] = [' ']
        lookup[151] = [' ']
        lookup[152] = ['~']
        lookup[153] = ['(', 'T', 'M', ')']
        lookup[154] = ['s']
        lookup[155] = ['>']
        lookup[156] = ['o', 'e']
        lookup[157] = [' ']
        lookup[158] = ['z']
        lookup[159] = ['Y']
        lookup[160] = [' ']
        lookup[161] = [' ']
        lookup[162] = ['c']
        lookup[163] = ['L']
        lookup[164] = ['$']
        lookup[165] = ['Y']
        lookup[166] = [' ']
        lookup[167] = ['S']
        lookup[168] = ['.', '.']
        lookup[169] = ['(', 'c', ')']
        lookup[170] = ['a']
        lookup[171] = ['"']
        lookup[172] = ['!']
        lookup[173] = ['-']
        lookup[174] = ['(', 'R', ')']
        lookup[175] = [' ']
        lookup[176] = [' ']
        lookup[177] = ['+', '-']
        lookup[178] = ['2']
        lookup[179] = ['3']
        lookup[180] = ['\'']
        lookup[181] = ['u']
        lookup[182] = [' ']
        lookup[183] = ['.']
        lookup[184] = ['_']
        lookup[185] = ['1']
        lookup[186] = ['o']
        lookup[187] = [' ']
        lookup[188] = ['1', '/', '4']
        lookup[189] = ['2', '/', '4']
        lookup[190] = ['3', '/', '4']
        lookup[191] = ['?']
        lookup[192] = ['A']
        lookup[193] = ['A']
        lookup[194] = ['A']
        lookup[195] = ['A']
        lookup[196] = ['A']
        lookup[197] = ['A']
        lookup[198] = ['A', 'E']
        lookup[199] = ['C']
        lookup[200] = ['E']
        lookup[201] = ['E']
        lookup[202] = ['E']
        lookup[203] = ['E']
        lookup[204] = ['I']
        lookup[205] = ['I']
        lookup[206] = ['I']
        lookup[207] = ['I']
        lookup[208] = ['D']
        lookup[209] = ['N']
        lookup[210] = ['O']
        lookup[211] = ['O']
        lookup[212] = ['O']
        lookup[213] = ['O']
        lookup[214] = ['O']
        lookup[215] = ['x']
        lookup[216] = ['O']
        lookup[217] = ['U']
        lookup[218] = ['U']
        lookup[219] = ['U']
        lookup[220] = ['U']
        lookup[221] = ['Y']
        lookup[222] = ['P']
        lookup[223] = ['s', 's']
        lookup[224] = ['a']
        lookup[225] = ['a']
        lookup[226] = ['a']
        lookup[227] = ['a']
        lookup[228] = ['a']
        lookup[229] = ['a']
        lookup[230] = ['a', 'e']
        lookup[231] = ['c']
        lookup[232] = ['e']
        lookup[233] = ['e']
        lookup[234] = ['e']
        lookup[235] = ['e']
        lookup[236] = ['i']
        lookup[237] = ['i']
        lookup[238] = ['i']
        lookup[239] = ['i']
        lookup[240] = ['d']
        lookup[241] = ['n']
        lookup[242] = ['o']
        lookup[243] = ['o']
        lookup[244] = ['o']
        lookup[245] = ['o']
        lookup[246] = ['o']
        lookup[247] = ['/']
        lookup[248] = ['o']
        lookup[249] = ['u']
        lookup[250] = ['u']
        lookup[251] = ['u']
        lookup[252] = ['u']
        lookup[253] = ['y']
        lookup[254] = ['b']
        lookup[255] = ['y']
        lookup[289] = ['g']
        lookup[297] = ['i']
        lookup[301] = ['i']
        lookup[311] = ['k']
        lookup[324] = ['n']
        lookup[328] = ['n']
        lookup[338] = [' ']
        lookup[339] = [' ']
        lookup[341] = ['r']
        lookup[352] = ['S']
        lookup[353] = ['s']
        lookup[357] = ['t']
        lookup[367] = ['u']
        lookup[375] = ['y']
        lookup[376] = [' ']
        lookup[381] = [' ']
        lookup[382] = [' ']
        lookup[402] = [' ']
        lookup[710] = [' ']
        lookup[732] = [' ']
        lookup[8211] = [' ']
        lookup[8212] = [' ']
        lookup[8216] = [' ']
        lookup[8217] = [' ']
        lookup[8218] = [' ']
        lookup[8220] = ['"']
        lookup[8221] = ['"']
        lookup[8222] = [' ']
        lookup[8224] = [' ']
        lookup[8226] = [' ']
        lookup[8230] = [' ']
        lookup[8240] = [' ']
        lookup[8249] = [' ']
        lookup[8250] = [' ']
        lookup[8364] = [' ']
        lookup[8482] = [' ']
        lookup[9632] = [' ']

        /* some addl cases for msft utf8s, mostly latin */
        lookup[915] = ['T']
        lookup[920] = ['O']
        lookup[931] = ['E']
        lookup[945] = ['a']
        lookup[949] = ['e']
        lookup[963] = ['s']
        lookup[964] = ['t']
        lookup[934] = ['p']
        lookup[960] = ['p', 'i']
        lookup[966] = ['P']
        lookup[8734] = ['o', 'o']
        lookup[8359] = ['P', 't', 's']
        lookup[9617] = [' ']
        lookup[9618] = [' ']
        lookup[9619] = [' ']
        lookup[9532] = ['+']
        lookup[9574] = ['T']
        lookup[9553] = ['|', '|']
        lookup[8992] = [' ']
        lookup[8993] = [' ']
        lookup[9508] = [' ']
        lookup[9474] = ['|']
        lookup[9516] = ['t']
        lookup[8745] = ['=']
        lookup[8801] = ['+', '-']
        lookup[8805] = ['>', '=']
        lookup[8804] = ['<', '=']
        lookup[8776] = ['~']
        lookup[8729] = ['.']
        lookup[8730] = ['V']
        lookup[8319] = ['n']
        lookup[9566] = [' ']
        lookup[9571] = [' ']
        lookup[9564] = [' ']
        lookup[9563] = [' ']
        lookup[9557] = [' ']
        lookup[8976] = [' ']
        lookup[9569] = [' ']
        lookup[9570] = [' ']
        lookup[9558] = [' ']
        lookup[9559] = [' ']
        lookup[9565] = [' ']
    }
}
